server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Configurazione specifica per le SPA (come Vite)
    location / {
        try_files $uri $uri/ /index.html;
        # Disabilita cache per index.html per evitare problemi di aggiornamento
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    # Configurazione per gli asset (JS, CSS, immagini) che hanno l'hash nel nome
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public";
    }
}